---
- name: Generate iden_table.dat from template
  ansible.builtin.template:
    src: templates/configs/iden_table.dat.j2
    dest: "/opt/{{ dvm_folder }}/configs/iden_table.dat"

- name: Generate CC configuration from template
  ansible.builtin.template:
    src: templates/configs/configCC.yml.j2
    dest: "/opt/{{ dvm_folder }}/configs/configCC.yml"

- name: Generate VC1 configuration from template
  ansible.builtin.template:
    src: templates/configs/configVC1.yml.j2
    dest: "/opt/{{ dvm_folder }}/configs/configVC1.yml"

- name: Generate VC2 configuration from template
  ansible.builtin.template:
    src: templates/configs/configVC2.yml.j2
    dest: "/opt/{{ dvm_folder }}/configs/configVC2.yml"
  when: dual_voice_channel | bool

- name: Load RID configuration data
  ansible.builtin.include_vars:
    file: "{{ rid_config_file }}"
    name: rid_data

- name: Generate RID configuration from template
  ansible.builtin.template:
    src: templates/configs/rid_acl.dat.j2
    dest: "/opt/{{ dvm_folder }}/configs/rid_acl.dat"
  vars:
    ridlist: "{{ rid_data.rid_list }}"

- name: Copy talkgroup_rules.yml to target
  ansible.builtin.copy:
    src: "{{ role_path }}/templates/default_configs/talkgroup_rules.yml"
    dest: "/opt/{{ dvm_folder }}/configs/talkgroup_rules.yml"
    owner: root
    group: root
    mode: '0755'
